### ISSUE TITLE
Handle redirect

### ISSUE THREAD

**Issue by Alex-CoolCats** [coolcatsnft/web3-widget#4]
Need to have a think about how best to handle this redirect:

https://github.com/coolcatsnft/web3-widget/blob/main/src/lib/providerOptions.js#L37

Maybe a config option?

**Comment by tzoeov** [comment]
Maybe we could get the current url and use that.

**Comment by Alex-CoolCats** [comment]
Yeah I did think that, wasn't sure about any security implications.
